[config]
reload_apps = true
source_color_index = 0


[templates.quickshell]
input_path = '~/.config/matugen/templates/Colors.qml'
output_path = '~/.config/quickshell/theme/Colors.qml'

[templates.niri]
input_path = '~/.config/matugen/templates/colors.kdl'
output_path = '~/.config/niri/colors.kdl'


[templates.neovim]
input_path = '~/.config/matugen/templates/neovim-colors.lua'
output_path = '~/.config/nvim/lua/config/colors.lua'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'kitty @ set-colors -a ~/.config/kitty/colors.conf 2>/dev/null || true'


