[config]
reload_apps = true
source_color_index = 0


[templates.quickshell]
input_path = '~/.config/quickshell/assets/matugen/quickshell-colors.json'
output_path = '~/.local/state/quickshell/colors.json'

[templates.niri]
input_path = '~/.config/matugen/templates/colors.kdl'
output_path = '~/.config/niri/colors.kdl'


[templates.neovim]
input_path = '~/.config/matugen/templates/neovim-colors.lua'
output_path = '~/.config/nvim/lua/config/colors.lua'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'kitty @ set-colors -a ~/.config/kitty/colors.conf 2>/dev/null || true'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify-color.ini'
output_path = '~/.config/spicetify/Themes/Matugen/color.ini'
post_hook = 'spicetify apply -n 2>/dev/null || true'



